# the goal is to store items as images, url links...
# then long term I want the system to be able to generate an outfit based on certain tags
# tags like winter, summer, fall/autumn, spring, color, warm-light, cool-light, dress, pants, business professional, smart business, etc
# I'll have to store clothing 

class Clothing_Article:
    def __init__(self, name, brand, in_wardrobe, date_bought):
        self.name = name
        self.brand = brand
        self.in_wardrobe = in_wardrobe



        # urls may need to be self entered...
        self.urls = []

        # prices...
        self.prices = []

        # date bought...
        self.date_bought = date_bought

        # colors are to be generated by the program
        self.colors = []

        # tags may be able to be generated
        self.tags = []
